import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={"antialiased bg-[#131418] text-white"}
      > 
        <main className="text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
